service:
    user: http://user-service.calabrio-private-dev:8082
    tenant: http://tenant-service.microservice-poc:8083
    project: http://project-service.microservice-poc:8085
    authtoken: http://auth-token-service.microservice-poc:8079
    c1: http://internal-arcus-c1-internal-ALB-1062579350.us-east-2.elb.amazonaws.com
spring:
    rabbitmq:
        username: user
        password: 2amxiKWwnN
        host: rabbitmq.rabbitmq
        port: 5672