service:
     user: http://user-service:8082
    tenant: http://tenant-service:8083
    project: http://project-service.calabrio-private-dev:8085
    authtoken: http://authtoken-service.calabrio-private-dev:8079
    c1: http://internal-arcus-c1-internal-ALB-1062579350.us-east-2.elb.amazonaws.com
spring:
    rabbitmq:
        username: user
        password: teMD5qLsg3
        host: rabbitmq.rabbitmq
        port: 5672
